Homewrok4
DariaZhdanova-dev/devops_training pull request #4
Opened 2021-12-14 20:05 UTC by DariaZhdanova-dev

@Cakemanator

2021-12-16 06:45 UTC, Cakemanator requested changes

2021-12-16 06:45 UTC, Cakemanator commented on task1
> +
Can't see changes regarding "All new accounts should change their passwords every 30 days."

2021-12-16 16:08 UTC, DariaZhdanova-dev commented on task1
> +
Добавила изменения в task1 ( task1+30, изменения файла /etc/login.defs)
Не совсем поняла, как вычленить именно новые аккаунты группы, поэтому сделала цикл по всем юзерам группы, надеюсь, не совсем не то

2021-12-17 12:51 UTC, Cakemanator approved these changes

2021-12-17 12:51 UTC, Cakemanator commented on task1
> +
Речь шла именно про `/etc/login.defs` )

2021-12-23 16:22 UTC, merged